"""
PostgreSQL compatibility shim.

The entire codebase (~90 files) was written against sqlite3's cursor
API: `?` positional placeholders, `cursor.lastrowid` after an INSERT,
and `PRAGMA table_info(table)` for the additive-migration functions
in database.py. Rewriting every call site to a Postgres-native style
(`%s` placeholders, `RETURNING id`, `information_schema.columns`)
would touch dozens of already-tested files and risk breaking things
that work today.

Instead, this shim translates at the boundary: every query written
in SQLite style is rewritten right before execution, so callers never
need to know which database is actually running. This is what makes
Postgres support additive rather than a rewrite - see database.py's
get_connection() for where this is selected.

Known limits, stated plainly rather than silently:
  - `?` is replaced with `%s` by a straight positional swap. Safe
    here because no query in this codebase contains a literal
    question mark in a string constant - if one is ever added,
    it would need to be escaped or this shim revisited.
  - `PRAGMA table_info(x)` is translated to a matching query against
    information_schema.columns, returning the same
    (cid, name, type, notnull, dflt_value, pk) tuple shape the
    migration functions already expect. Only the columns those
    functions actually read (index 1: name) are populated with real
    data from Postgres; the rest are filled with SQLite-shaped
    placeholders sufficient for that tuple shape.
  - `AUTOINCREMENT` columns are rewritten to Postgres' `SERIAL`.
  - `.lastrowid` is emulated via `SELECT lastval()`, which returns
    the last value generated by a SERIAL/IDENTITY column on this
    connection - correct for the codebase's pattern of "insert one
    row, then read cursor.lastrowid", but not for multi-row inserts
    or inserts that don't touch a serial column.
"""

import re

_AUTOINCREMENT_RE = re.compile(
    r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE
)

_PRAGMA_TABLE_INFO_RE = re.compile(
    r"PRAGMA\s+table_info\(([a-zA-Z_][a-zA-Z0-9_]*)\)", re.IGNORECASE
)


def _translate_ddl(sql: str) -> str:
    return _AUTOINCREMENT_RE.sub("SERIAL PRIMARY KEY", sql)


def _translate_placeholders(sql: str) -> str:
    # Positional `?` -> `%s`. See module docstring for why this is
    # safe for this codebase's queries specifically.
    return sql.replace("?", "%s")


class PGCursorShim:
    def __init__(self, real_cursor, real_connection):
        self._cursor = real_cursor
        self._conn = real_connection
        self._pragma_table_info_rows = None

    def execute(self, sql, params=None):
        pragma_match = _PRAGMA_TABLE_INFO_RE.search(sql)
        if pragma_match:
            table_name = pragma_match.group(1)
            self._cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
                ORDER BY ordinal_position
                """,
                (table_name,),
            )
            rows = self._cursor.fetchall()
            # Match sqlite's PRAGMA table_info tuple shape:
            # (cid, name, type, notnull, dflt_value, pk). Callers in
            # this codebase only ever read index 1 (name), so the
            # rest are filled with harmless placeholders.
            self._pragma_table_info_rows = [
                (i, row[0], "", 0, None, 0) for i, row in enumerate(rows)
            ]
            return self

        self._pragma_table_info_rows = None

        sql = _translate_ddl(sql)
        sql = _translate_placeholders(sql)

        if params is None:
            self._cursor.execute(sql)
        else:
            self._cursor.execute(sql, tuple(params) if params else None)

        return self

    def fetchone(self):
        if self._pragma_table_info_rows is not None:
            return self._pragma_table_info_rows[0] if self._pragma_table_info_rows else None
        return self._cursor.fetchone()

    def fetchall(self):
        if self._pragma_table_info_rows is not None:
            return self._pragma_table_info_rows
        return self._cursor.fetchall()

    @property
    def lastrowid(self):
        # Emulates sqlite3's cursor.lastrowid: valid immediately
        # after an INSERT into a table with a SERIAL/IDENTITY column
        # on this same connection. See module docstring for the
        # scope of this emulation.
        try:
            self._cursor.execute("SELECT lastval()")
            return self._cursor.fetchone()[0]
        except Exception:
            return None

    def __getattr__(self, name):
        # Anything not explicitly shimmed above (rowcount, description,
        # etc.) passes straight through to the real cursor.
        return getattr(self._cursor, name)


class PGConnectionShim:
    def __init__(self, real_connection):
        self._conn = real_connection

    def cursor(self):
        return PGCursorShim(self._conn.cursor(), self._conn)

    def execute(self, sql, params=None):
        # A handful of call sites use conn.execute(...) directly
        # (e.g. `conn.execute("PRAGMA foreign_keys = ON")`).
        if sql.strip().upper().startswith("PRAGMA"):
            return  # No-op: Postgres enforces foreign keys natively.
        cur = self.cursor()
        cur.execute(sql, params)
        return cur

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def __getattr__(self, name):
        return getattr(self._conn, name)
